# Generated by Django 6.0.2 on 2026-02-20 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What the money was spent on.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional details, receipts info, etc.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent (CZK).', max_digits=8)),
                ('category', models.CharField(choices=[('trip', 'Trip / Excursion'), ('supplies', 'Supplies'), ('food', 'Food & Drinks'), ('decoration', 'Decoration'), ('donation', 'Donation'), ('other', 'Other')], default='other', max_length=20)),
                ('spent_at', models.DateField(default=django.utils.timezone.now, help_text='Date the expense occurred.')),
                ('is_published', models.BooleanField(default=True, help_text='If True, all logged-in students can see this expense.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(help_text='Treasurer who logged this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-spent_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of what the payment is for.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation (event details, itemised costs, etc.).')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount each assigned student is expected to pay (CZK).', max_digits=8)),
                ('due_date', models.DateField(blank=True, help_text='Optional deadline for payment.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assign_to_all', models.BooleanField(default=True, help_text="If True, every active student is expected to pay. If False, only the students listed in 'assigned_to'.")),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Specific students assigned to this request (used when assign_to_all=False).', related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Treasurer who created this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount actually transferred (CZK).', max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note from the student or treasurer (e.g. bank reference).')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the student claims to have sent the money.', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the treasurer confirmed receipt.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_request', models.ForeignKey(help_text='The payment request this transaction is paying towards.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.paymentrequest')),
                ('student', models.ForeignKey(help_text='Student who made this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
