# Generated by Django 6.0.2 on 2026-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expense_paymentrequest_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text="Account holder name (e.g. 'Class 4.B Fund').", max_length=200)),
                ('account_number', models.CharField(help_text="Local account number (e.g. '123456789/0800').", max_length=50)),
                ('iban', models.CharField(blank=True, help_text='IBAN (optional, used in the QR code).', max_length=34)),
                ('bank_name', models.CharField(blank=True, help_text="Bank name (e.g. 'Česká spořitelna').", max_length=100)),
                ('note', models.TextField(blank=True, help_text="Any extra instructions for students (e.g. 'always include your name as the message').")),
                ('is_active', models.BooleanField(default=True, help_text='Only the active account is shown to students.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
    ]
