# Generated by Django 6.0.2 on 2026-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='specific_symbol',
            field=models.CharField(blank=True, help_text='Up to 10 digits. Optionally used to identify the payer.', max_length=10, verbose_name='Specific Symbol (SS)'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='variable_symbol',
            field=models.CharField(blank=True, help_text='Up to 10 digits. Used to identify the payment purpose at the bank.', max_length=10, verbose_name='Variable Symbol (VS)'),
        ),
    ]
