# Generated by Django 6.0.2 on 2026-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paymentrequest_specific_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_fund_balance',
            field=models.BooleanField(default=False, help_text="When checked, the class fund balance card is hidden on this user's dashboard.", verbose_name='Hide fund balance'),
        ),
    ]
