# Generated by Django 6.0.2 on 2026-03-20 10:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('system_admin', 'System Admin'), ('treasurer_full', 'Treasurer (Full)'), ('treasurer_accountant', 'Treasurer (Accountant)'), ('treasurer_bookkeeper', 'Treasurer (Bookkeeper)'), ('student', 'Student'), ('parent', 'Parent')], default='student', help_text='Determines what this user can see and do in the application.', max_length=30, verbose_name='Role')),
                ('hide_fund_balance', models.BooleanField(default=False, help_text="When checked, the class fund balance card is hidden on this user's dashboard.", verbose_name='Hide fund balance')),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts_customuser_set', related_query_name='accounts_customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts_customuser_set', related_query_name='accounts_customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable class name, e.g. "4.B – 2026".', max_length=100, unique=True)),
                ('school_year', models.CharField(blank=True, help_text='Optional school year label, e.g. "2025/2026".', max_length=20)),
                ('vs_prefix', models.CharField(blank=True, help_text='2-digit numeric prefix for auto-generated Variable Symbols in this class (e.g. "04" → students get VS 04001, 04002 …). Leave blank to use random 6-digit fallback values.', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{0,2}$', 'VS Prefix must be 0–2 digits.')], verbose_name='VS Prefix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, help_text='Primary teacher/treasurer responsible for this class.', limit_choices_to={'role__in': ['treasurer_full', 'treasurer_accountant', 'treasurer_bookkeeper']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short, descriptive group name shown in the admin panel and navbar.', max_length=100)),
                ('can_log_expenses', models.BooleanField(default=True, help_text='Members may add new expense records.', verbose_name='Log expenses')),
                ('can_manage_payment_requests', models.BooleanField(default=False, help_text='Members may create, edit, and confirm payment requests.', verbose_name='Manage payment requests')),
                ('can_view_bank_account', models.BooleanField(default=False, help_text='Members may see and update the class bank account details.', verbose_name='View / edit bank account')),
                ('can_manage_students', models.BooleanField(default=False, help_text='Members may add, edit, or remove student profiles.', verbose_name='Manage students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(help_text='The class this group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fund_groups', to='accounts.schoolclass')),
            ],
            options={
                'verbose_name': 'Fund Group',
                'verbose_name_plural': 'Fund Groups',
                'ordering': ['school_class', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_symbol', models.CharField(blank=True, help_text="Unique 1–10-digit code used to match this student's bank transfers. Leave blank to auto-generate from the class VS prefix.", max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Variable Symbol must be 1–10 digits.', regex='^\\d{1,10}$')], verbose_name='Variable Symbol (VS)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to exclude this student from new payment requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent/guardian linked to this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, help_text='The class this student belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.schoolclass')),
                ('user', models.OneToOneField(help_text="The student's own user account.", on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['school_class', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Treasurer who has access to this class.', limit_choices_to={'role__in': ['treasurer_full', 'treasurer_accountant', 'treasurer_bookkeeper', 'system_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL)),
                ('fund_group', models.ForeignKey(blank=True, help_text='The permission group that defines what this member can do.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.fundgroup')),
                ('school_class', models.ForeignKey(help_text='The class this membership entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.schoolclass')),
            ],
            options={
                'verbose_name': 'Class Membership',
                'verbose_name_plural': 'Class Memberships',
                'ordering': ['school_class', 'user__last_name'],
                'unique_together': {('school_class', 'user')},
            },
        ),
    ]
