# Generated by Django 6.0.2 on 2026-02-23 15:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_treasurer', models.BooleanField(default=False, help_text='Designates whether this user is the class treasurer with administrative privileges over the fund.', verbose_name='Treasurer')),
                ('hide_fund_balance', models.BooleanField(default=False, help_text="When checked, the class fund balance card is hidden on this user's dashboard.", verbose_name='Hide fund balance')),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts_customuser_set', related_query_name='accounts_customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts_customuser_set', related_query_name='accounts_customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable class name, e.g. "4.B – 2026".', max_length=100, unique=True)),
                ('school_year', models.CharField(blank=True, help_text='Optional school year label, e.g. "2025/2026".', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, help_text='The teacher/treasurer responsible for this class.', limit_choices_to={'is_treasurer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(help_text='Full name of the child (displayed on treasurer dashboards).', max_length=200)),
                ('variable_symbol', models.CharField(help_text="Unique up-to-10-digit code used to identify this student's bank transfers.", max_length=10, unique=True, verbose_name='Variable Symbol (VS)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to exclude this student from new payment requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(help_text='The parent/guardian who will receive payment requests and pay.', limit_choices_to={'is_treasurer': False}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(help_text='The class this student belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.schoolclass')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['school_class', 'child_name'],
            },
        ),
    ]
