# Generated by Django 6.0.2 on 2026-02-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_user_centric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_treasurer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('treasurer', 'Class Treasurer / Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='student', help_text='Determines what this user can see and do in the application.', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='The teacher/treasurer responsible for this class.', limit_choices_to={'role': 'treasurer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
