# Generated by Django 6.0.2 on 2026-02-24 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_based_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='vs_prefix',
            field=models.CharField(blank=True, help_text='2-digit numeric prefix for auto-generated Variable Symbols in this class (e.g. "04" → students get VS 04001, 04002 …). Leave blank to use random 6-digit fallback values.', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{0,2}$', 'VS Prefix must be 0–2 digits.')], verbose_name='VS Prefix'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='variable_symbol',
            field=models.CharField(blank=True, help_text="Unique 1–10-digit code used to match this student's bank transfers. Leave blank to auto-generate from the class VS prefix.", max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Variable Symbol must be 1–10 digits.', regex='^\\d{1,10}$')], verbose_name='Variable Symbol (VS)'),
        ),
    ]
