# Generated by Django 6.0.2 on 2026-02-25 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vs_auto_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('treasurer_full', 'Treasurer (Full)'), ('treasurer_accountant', 'Treasurer (Accountant)'), ('treasurer_bookkeeper', 'Treasurer (Bookkeeper)'), ('student', 'Student'), ('parent', 'Parent')], default='student', help_text='Determines what this user can see and do in the application.', max_length=30, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Primary teacher/treasurer responsible for this class.', limit_choices_to={'role__in': ['treasurer_full', 'treasurer_accountant', 'treasurer_bookkeeper']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('full', 'Full (all permissions)'), ('accountant', 'Accountant (expenses + payment requests)'), ('bookkeeper', 'Bookkeeper (expenses only)')], default='full', help_text='What this member is allowed to do in this class.', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(help_text='The class this membership entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.schoolclass')),
                ('user', models.ForeignKey(help_text='Treasurer who has access to this class.', limit_choices_to={'role__in': ['treasurer_full', 'treasurer_accountant', 'treasurer_bookkeeper', 'system_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Membership',
                'verbose_name_plural': 'Class Memberships',
                'ordering': ['school_class', 'tier', 'user__last_name'],
                'unique_together': {('school_class', 'user')},
            },
        ),
    ]
