# Generated by Django 6.0.2 on 2026-02-25 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_treasurer_tiers_and_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmembership',
            options={'ordering': ['school_class', 'user__last_name'], 'verbose_name': 'Class Membership', 'verbose_name_plural': 'Class Memberships'},
        ),
        migrations.RemoveField(
            model_name='classmembership',
            name='tier',
        ),
        migrations.CreateModel(
            name='FundGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short, descriptive group name shown in the admin panel and navbar.', max_length=100)),
                ('can_log_expenses', models.BooleanField(default=True, help_text='Members may add new expense records.', verbose_name='Log expenses')),
                ('can_manage_payment_requests', models.BooleanField(default=False, help_text='Members may create, edit, and confirm payment requests.', verbose_name='Manage payment requests')),
                ('can_view_bank_account', models.BooleanField(default=False, help_text='Members may see and update the class bank account details.', verbose_name='View / edit bank account')),
                ('can_manage_students', models.BooleanField(default=False, help_text='Members may add, edit, or remove student profiles.', verbose_name='Manage students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(help_text='The class this group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='fund_groups', to='accounts.schoolclass')),
            ],
            options={
                'verbose_name': 'Fund Group',
                'verbose_name_plural': 'Fund Groups',
                'ordering': ['school_class', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
        migrations.AddField(
            model_name='classmembership',
            name='fund_group',
            field=models.ForeignKey(blank=True, help_text='The permission group that defines what this member can do.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.fundgroup'),
        ),
    ]
