# Generated by Django 6.0.2 on 2026-02-23 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('payment_reminder', 'Payment Reminder'), ('receipt', 'Payment Receipt'), ('custom', 'Custom Message')], default='payment_reminder', max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, help_text='Email subject line or SMS header.', max_length=255)),
                ('body_preview', models.TextField(blank=True, help_text='First 500 characters of the message body (for the audit log).')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True, help_text='False if the send attempt failed (e.g. bounce, SMTP error).')),
                ('error_message', models.TextField(blank=True, help_text='Error details if success=False.')),
                ('payment_request', models.ForeignKey(blank=True, help_text='The payment request this reminder is about (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='finances.paymentrequest')),
                ('recipient', models.ForeignKey(help_text='The user (parent) who received this notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
