# Generated by Django 6.0.2 on 2026-02-23 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text="Account holder name (e.g. 'Class 4.B Fund').", max_length=200)),
                ('account_number', models.CharField(help_text="Local account number (e.g. '123456789/0800').", max_length=50)),
                ('iban', models.CharField(blank=True, help_text='IBAN (optional, used in the QR code).', max_length=34)),
                ('bank_name', models.CharField(blank=True, help_text="Bank name (e.g. 'Česká spořitelna').", max_length=100)),
                ('note', models.TextField(blank=True, help_text='Any extra instructions for students.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active account is shown to students.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.OneToOneField(blank=True, help_text='The class this bank account belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account', to='accounts.schoolclass')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('trip', 'Trip / Excursion'), ('supplies', 'Supplies'), ('food', 'Food & Drinks'), ('decoration', 'Decoration'), ('donation', 'Donation'), ('other', 'Other')], default='other', max_length=20)),
                ('spent_at', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True, help_text='If True, all logged-in students can see this expense.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-spent_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of what the payment is for.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount each assigned student is expected to pay (CZK).', max_digits=8)),
                ('due_date', models.DateField(blank=True, help_text='Optional deadline for payment.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variable_symbol', models.CharField(blank=True, help_text='Up to 10 digits — identifies the payment purpose.', max_length=10, verbose_name='Variable Symbol (VS)')),
                ('specific_symbol', models.CharField(blank=True, help_text='Up to 10 digits — optionally identifies the payer.', max_length=10, verbose_name='Specific Symbol (SS)')),
                ('assign_to_all', models.BooleanField(default=True, help_text='If True, every active student is expected to pay.')),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Specific students assigned to this request (used when assign_to_all=False).', related_name='finances_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Treasurer who created this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_created_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.paymentrequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
