# Generated by Django 6.0.2 on 2026-02-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_schoolclass_studentprofile'),
        ('finances', '0002_add_school_class_to_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='The class this expense belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounts.schoolclass'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='The class this payment request belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='accounts.schoolclass'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='The class this transaction belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.schoolclass'),
        ),
    ]
