# Generated by Django 6.0.2 on 2026-02-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_add_school_class_to_payment_transaction_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bic',
            field=models.CharField(blank=True, help_text='BIC/SWIFT code (optional, e.g. "GIBACZPX").', max_length=11, verbose_name='BIC / SWIFT'),
        ),
    ]
