name: Deploy Django Project

on:
  push:
    branches:
      - main # Change this if your default branch is 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute deployment script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the directory where your script is and run it
            cd ~/2025_wt_prj_dembinny/
            ./deploy.sh
